### ISSUE TITLE
Options in places widget are not passed

### ISSUE THREAD

**Issue by ulrichlehner** [punkave/apostrophe-places#23]
It looks like there's a bug in the widget code: https://github.com/apostrophecms/apostrophe-places/blob/4ad0203d0a7f296e568c705b90ead0f0923a45ad/lib/modules/apostrophe-places-widgets/public/js/always.js#L8-L9

The method `_.merge()` should probably be called with `_options` instead of `_.options`. Currently no options are passed to the following `addMap()` method.

**Comment by boutell** [comment]
This module is not, unfortunately, in the best of shape. We are considering, instead, creating a simple module that provides a "geolocatable behavior" for pieces configured to use it, i.e. server-side geolocation, and also a sample project that uses it with google maps. The front end provided with this module never really caught on across a large number of our projects.

That being said, you're clearly right about that, and a PR would be accepted.
